[pytest]
markers =
    smoke: mark a test as smoke scenario
    valid: mark a test as valid scenario
    regression: mark a test as regression scenario
    security: mark a test as security scenario
    performance: mark a test as performance scenario
    positive: mark a test as positive scenario
    negative: mark a test as negative scenario
    boundary: mark a test as boundary scenario
    edge: mark a test as edge scenario
    precision: mark a test as precision scenario
    invalid: mark a test as invalid scenario
