# ********RoostGPT********
"""
Test generated by RoostGPT for test amanuserLanguage5June using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=modulus_a78485441a
ROOST_METHOD_SIG_HASH=modulus_36a969db72


                                 תרחיש 1: בדיקת מקרה עם שני מספרים שלמים חיוביים
                                                                          פרטים:
                                  שם הבדיקה: test_modulus_with_positive_integers
.תיאור: הבדיקה מתוכנתת לאמת את התוצאה של הפונקציה כאשר הפרמטרים הם שני מספרים שלמים חיוביים
                                                                          ביצוע:
                                        .הכנה: אין צורך בהכנה מיוחדת לבדיקה זו
                             .פעולה: נקרא לפונקציה עם שני מספרים שלמים חיוביים
         .אימות: נבדוק שהתוצאה היא השארית של החלוקה של המספר הראשון במספר השני
                                                                          אימות:
.הצדקה: הבדיקה חשובה כדי לוודא שהפונקציה מחזירה את התוצאה הנכונה במקרה הכללי של שני מספרים שלמים חיוביים
                                                                                
                                      תרחיש 2: בדיקת מקרה שבו המספר השני הוא אפס
                                                                          פרטים:
                                               שם הבדיקה: test_modulus_with_zero
     .תיאור: הבדיקה מתוכנתת לאמת את התוצאה של הפונקציה כאשר המספר השני הוא אפס
                                                                          ביצוע:
                                        .הכנה: אין צורך בהכנה מיוחדת לבדיקה זו
                                  .פעולה: נקרא לפונקציה עם מספר שלם חיובי ואפס
             .אימות: נבדוק שהתוצאה היא ההודעה "Cannot perform modulus by zero"
                                                                          אימות:
.הצדקה: הבדיקה חשובה כדי לוודא שהפונקציה מחזירה הודעת שגיאה מתאימה כאשר מנסים לחלק באפס
                                                                                
"""

# ********RoostGPT********
import pytest
from calc import SimpleCalculator

class Test_SimpleCalculatorModulus:
    def test_modulus_with_positive_integers(self):
        calculator = SimpleCalculator()
        result = calculator.modulus(10, 3)
        assert result == 1, "Expected Result: 1, Got: {}".format(result)

    def test_modulus_with_zero(self):
        calculator = SimpleCalculator()
        result = calculator.modulus(10, 0)
        assert result == "Cannot perform modulus by zero", "Expected Result: Cannot perform modulus by zero, Got: {}".format(result)
