# ********RoostGPT********
"""
Test generated by RoostGPT for test Pytest using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=division_641e53a5f9
ROOST_METHOD_SIG_HASH=division_eae366bb2d


Scenario 1: Division by a Non-Zero Number
Details:
  TestName: test_division_by_non_zero
  Description: This test verifies that the function correctly performs division when the divisor is a non-zero number.
Execution:
  Arrange: Prepare two numbers, num1 and num2, where num2 is not zero.
  Act: Call the division function with num1 and num2 as arguments.
  Assert: Check that the result is equal to the expected quotient of num1 divided by num2.
Validation:
  This test is crucial to ensure that the basic functionality of division is working as expected when the divisor is a valid non-zero number.

Scenario 2: Division by Zero
Details:
  TestName: test_division_by_zero
  Description: This test checks that the function handles division by zero correctly by returning an appropriate error message.
Execution:
  Arrange: Prepare two numbers, num1 and num2, where num2 is zero.
  Act: Call the division function with num1 and num2 as arguments.
  Assert: Verify that the function returns the string "Cannot divide by zero".
Validation:
  This test is important to confirm that the function adheres to the mathematical rule that division by zero is undefined and handles it gracefully.

Scenario 3: Division Resulting in a Fraction
Details:
  TestName: test_division_resulting_in_fraction
  Description: This test ensures that the function can handle cases where the division results in a fractional number.
Execution:
  Arrange: Prepare two numbers, num1 and num2, where num1 is not a multiple of num2.
  Act: Call the division function with num1 and num2 as arguments.
  Assert: Check that the result is a floating-point number representing the correct quotient.
Validation:
  This test is necessary to verify that the function can return fractional results, which are common in division operations.

Scenario 4: Division Resulting in a Whole Number
Details:
  TestName: test_division_resulting_in_whole_number
  Description: This test checks that the function correctly returns a whole number when the division results in an integer.
Execution:
  Arrange: Prepare two numbers, num1 and num2, where num1 is a multiple of num2.
  Act: Call the division function with num1 and num2 as arguments.
  Assert: Ensure that the result is an integer representing the correct quotient.
Validation:
  This test is important to confirm that the function can handle cases where the division results in a whole number, ensuring accuracy in such scenarios.

Scenario 5: Division with Negative Numbers
Details:
  TestName: test_division_with_negative_numbers
  Description: This test verifies that the function correctly handles division when one or both numbers are negative.
Execution:
  Arrange: Prepare two numbers, num1 and num2, where at least one of them is negative.
  Act: Call the division function with num1 and num2 as arguments.
  Assert: Check that the result is the correct quotient, taking into account the sign of the numbers.
Validation:
  This test is crucial to ensure that the function can accurately perform division with negative numbers, which is a common requirement in mathematical operations.

"""

# ********RoostGPT********
import pytest
from calc import division

class Test_CalcDivision:

    @pytest.mark.positive
    def test_division_by_non_zero(self):
        # Arrange
        num1 = 10
        num2 = 2
        expected_result = 5

        # Act
        result = division(num1, num2)

        # Assert
        assert result == expected_result, f"Expected {expected_result}, got {result}"

    @pytest.mark.negative
    def test_division_by_zero(self):
        # Arrange
        num1 = 10
        num2 = 0
        expected_result = "Cannot divide by zero"

        # Act
        result = division(num1, num2)

        # Assert
        assert result == expected_result, f"Expected '{expected_result}', got '{result}'"

    @pytest.mark.positive
    def test_division_resulting_in_fraction(self):
        # Arrange
        num1 = 7
        num2 = 3
        expected_result = 7 / 3

        # Act
        result = division(num1, num2)

        # Assert
        assert result == expected_result, f"Expected {expected_result}, got {result}"

    @pytest.mark.positive
    def test_division_resulting_in_whole_number(self):
        # Arrange
        num1 = 8
        num2 = 4
        expected_result = 2

        # Act
        result = division(num1, num2)

        # Assert
        assert result == expected_result, f"Expected {expected_result}, got {result}"

    @pytest.mark.positive
    def test_division_with_negative_numbers(self):
        # Arrange
        num1 = -10
        num2 = 2
        expected_result = -5

        # Act
        result = division(num1, num2)

        # Assert
        assert result == expected_result, f"Expected {expected_result}, got {result}"

        # Arrange
        num1 = 10
        num2 = -2
        expected_result = -5

        # Act
        result = division(num1, num2)

        # Assert
        assert result == expected_result, f"Expected {expected_result}, got {result}"

        # Arrange
        num1 = -10
        num2 = -2
        expected_result = 5

        # Act
        result = division(num1, num2)

        # Assert
        assert result == expected_result, f"Expected {expected_result}, got {result}"
