# ********RoostGPT********
"""
Test generated by RoostGPT for test PythonTest111 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=SimpleCalculator.subtraction_68d9a9a59f
ROOST_METHOD_SIG_HASH=SimpleCalculator.subtraction_c085e74db2


Scenario 1: Test subtraction of two positive numbers
Details:
  TestName: test_subtraction_positive_numbers
  Description: This test is intended to verify that the subtraction function correctly subtracts two positive numbers.
Execution:
  Arrange: No specific setup is required as the function does not depend on any state.
  Act: Invoke the subtraction function with two positive numbers, for example, subtraction(5, 3).
  Assert: Check that the result is correct, in this case, it should be 2.
Validation:
  The subtraction of two positive numbers is a basic operation that the function must handle correctly. The expected result is based on the standard rules of arithmetic.

Scenario 2: Test subtraction of two negative numbers
Details:
  TestName: test_subtraction_negative_numbers
  Description: This test is intended to verify that the subtraction function correctly subtracts two negative numbers.
Execution:
  Arrange: No specific setup is required as the function does not depend on any state.
  Act: Invoke the subtraction function with two negative numbers, for example, subtraction(-5, -3).
  Assert: Check that the result is correct, in this case, it should be -2.
Validation:
  The subtraction of two negative numbers is a basic operation that the function must handle correctly. The expected result is based on the standard rules of arithmetic.

Scenario 3: Test subtraction of a positive number and a negative number
Details:
  TestName: test_subtraction_positive_negative_numbers
  Description: This test is intended to verify that the subtraction function correctly subtracts a positive number and a negative number.
Execution:
  Arrange: No specific setup is required as the function does not depend on any state.
  Act: Invoke the subtraction function with a positive number and a negative number, for example, subtraction(5, -3).
  Assert: Check that the result is correct, in this case, it should be 8.
Validation:
  The subtraction of a positive number and a negative number is a basic operation that the function must handle correctly. The expected result is based on the standard rules of arithmetic.

Scenario 4: Test subtraction of zero and a number
Details:
  TestName: test_subtraction_zero_number
  Description: This test is intended to verify that the subtraction function correctly subtracts zero and a number.
Execution:
  Arrange: No specific setup is required as the function does not depend on any state.
  Act: Invoke the subtraction function with zero and a number, for example, subtraction(0, 5).
  Assert: Check that the result is correct, in this case, it should be -5.
Validation:
  The subtraction of zero and a number is a basic operation that the function must handle correctly. The expected result is based on the standard rules of arithmetic.

"""

# ********RoostGPT********
import pytest
from calc import SimpleCalculator

class Test_SimpleCalculatorSubtraction:

    @pytest.mark.regression
    def test_subtraction_positive_numbers(self):
        calc = SimpleCalculator()
        result = calc.subtraction(5, 3)
        assert result == 2, "Subtraction of two positive numbers failed"

    @pytest.mark.regression
    def test_subtraction_negative_numbers(self):
        calc = SimpleCalculator()
        result = calc.subtraction(-5, -3)
        assert result == -2, "Subtraction of two negative numbers failed"

    @pytest.mark.regression
    def test_subtraction_positive_negative_numbers(self):
        calc = SimpleCalculator()
        result = calc.subtraction(5, -3)
        assert result == 8, "Subtraction of a positive number and a negative number failed"

    @pytest.mark.regression
    def test_subtraction_zero_number(self):
        calc = SimpleCalculator()
        result = calc.subtraction(0, 5)
        assert result == -5, "Subtraction of zero and a number failed"
