# ********RoostGPT********
"""
Test generated by RoostGPT for test amanuserLanguage5June using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=addition_9ccff787e3
ROOST_METHOD_SIG_HASH=addition_77ffd3333b


Scenario 1: Testing addition of two positive numbers
Details:
  TestName: test_addition_positive_numbers
  Description: This test is intended to verify that the function correctly adds two positive numbers.
Execution:
  Arrange: No special setup is required as the function does not depend on any external state.
  Act: Invoke the function with two positive numbers, for example, addition(2, 3).
  Assert: Check that the function returns the correct sum, in this case, 5.
Validation:
  This test is important to ensure that the function correctly handles the most basic case of adding two positive numbers. The expected result is directly tied to the function's specifications and business requirements of performing addition.

Scenario 2: Testing addition of two negative numbers
Details:
  TestName: test_addition_negative_numbers
  Description: This test is intended to verify that the function correctly adds two negative numbers.
Execution:
  Arrange: No special setup is required as the function does not depend on any external state.
  Act: Invoke the function with two negative numbers, for example, addition(-2, -3).
  Assert: Check that the function returns the correct sum, in this case, -5.
Validation:
  This test is important to ensure that the function correctly handles the case of adding two negative numbers. The expected result is directly tied to the function's specifications and business requirements of performing addition.

Scenario 3: Testing addition of a positive number and a negative number
Details:
  TestName: test_addition_positive_negative_numbers
  Description: This test is intended to verify that the function correctly adds a positive number and a negative number.
Execution:
  Arrange: No special setup is required as the function does not depend on any external state.
  Act: Invoke the function with a positive number and a negative number, for example, addition(2, -3).
  Assert: Check that the function returns the correct sum, in this case, -1.
Validation:
  This test is important to ensure that the function correctly handles the case of adding a positive number and a negative number. The expected result is directly tied to the function's specifications and business requirements of performing addition.

Scenario 4: Testing addition of zero and a number
Details:
  TestName: test_addition_zero_number
  Description: This test is intended to verify that the function correctly adds zero and a number.
Execution:
  Arrange: No special setup is required as the function does not depend on any external state.
  Act: Invoke the function with zero and a number, for example, addition(0, 3).
  Assert: Check that the function returns the correct sum, in this case, 3.
Validation:
  This test is important to ensure that the function correctly handles the case of adding zero and a number. The expected result is directly tied to the function's specifications and business requirements of performing addition.

"""

# ********RoostGPT********
import pytest
from calc import SimpleCalculator

class Test_SimpleCalculatorAddition:
    def test_addition_positive_numbers(self):
        # Arrange
        calculator = SimpleCalculator()
        num1 = 2
        num2 = 3

        # Act
        result = calculator.addition(num1, num2)

        # Assert
        assert result == 5, "The sum of two positive numbers is incorrect"

    def test_addition_negative_numbers(self):
        # Arrange
        calculator = SimpleCalculator()
        num1 = -2
        num2 = -3

        # Act
        result = calculator.addition(num1, num2)

        # Assert
        assert result == -5, "The sum of two negative numbers is incorrect"

    def test_addition_positive_negative_numbers(self):
        # Arrange
        calculator = SimpleCalculator()
        num1 = 2
        num2 = -3

        # Act
        result = calculator.addition(num1, num2)

        # Assert
        assert result == -1, "The sum of a positive number and a negative number is incorrect"

    def test_addition_zero_number(self):
        # Arrange
        calculator = SimpleCalculator()
        num1 = 0
        num2 = 3

        # Act
        result = calculator.addition(num1, num2)

        # Assert
        assert result == 3, "The sum of zero and a number is incorrect"
