# ********RoostGPT********
"""
Test generated by RoostGPT for test amanuserLanguage5June using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=addition_9ccff787e3
ROOST_METHOD_SIG_HASH=addition_77ffd3333b


                                    תרחיש [1]: בדיקת חיבור של שני מספרים חיוביים
                                                                          פרטים:
                                שם הבדיקה: test_addition_of_two_positive_numbers
                   .תיאור: הבדיקה מתוכנתת לאמת את החיבור של שני מספרים חיוביים
                                                                           הרצה:
                                        .הכנה: אין צורך בהכנה מיוחדת לבדיקה זו
  .פעולה: נקרא לפונקציה addition עם שני מספרים חיוביים, לדוגמה, addition(3, 5)
                        .הצהרה: התוצאה המצופה היא הסכום של המספרים, במקרה זה 8
                                                                          אימות:
.הצדקה: הבדיקה חשובה כדי לוודא שהפונקציה מחזירה את התוצאה הנכונה עבור מספרים חיוביים
                                                                                
                                                                                
"""

# ********RoostGPT********
import pytest
from calc import SimpleCalculator

class Test_SimpleCalculatorAddition:
    def test_addition_of_two_positive_numbers(self):
        # Instantiate the calculator object
        calculator = SimpleCalculator()
        
        # Call the addition method with two positive numbers
        result = calculator.addition(3, 5)
        
        # Assert that the result is the sum of the two numbers
        assert result == 8, "The sum of 3 and 5 should be 8"
