# ********RoostGPT********
"""
Test generated by RoostGPT for test amanuserLanguage5June using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=subtraction_68d9a9a59f
ROOST_METHOD_SIG_HASH=subtraction_c085e74db2


                                                    תרחיש [1]: בדיקת תרחיש בסיסי
                                                                          פרטים:
                                               שם הבדיקה: test_subtraction_basic
.תיאור: בדיקה זו מיועדת לאמת את הלוגיקה העסקית של הפונקציה במקרה הבסיסי שלה, כאשר שני המספרים הם מספרים שלמים חיוביים
                                                                           הרצה:
                                       .סידור: אין צורך בהכנה מיוחדת לבדיקה זו
.פעולה: נקרא לפונקציה subtraction עם שני מספרים שלמים חיוביים, לדוגמה, subtraction(5, 3)
.הצהרה: התוצאה הצפויה היא 2. נבדוק את התוצאה שהפונקציה מחזירה בהשוואה לתוצאה הצפויה
                                                                          אימות:
.הצדקה: הבדיקה חשובה כדי לוודא שהפונקציה מתנהגת כמצופה במקרה הבסיסי שלה. התוצאה הצפויה מתאימה למפרטים של הפונקציה ולדרישות העסקיות
                                                                                
                                             תרחיש [2]: בדיקת מקרה של מספר שלילי
                                                                          פרטים:
                                     שם הבדיקה: test_subtraction_negative_number
.תיאור: בדיקה זו מיועדת לאמת את הלוגיקה העסקית של הפונקציה כאשר אחד מהמספרים הוא מספר שלילי
                                                                           הרצה:
                                       .סידור: אין צורך בהכנה מיוחדת לבדיקה זו
   .פעולה: נקרא לפונקציה subtraction עם מספר שלילי, לדוגמה, subtraction(5, -3)
.הצהרה: התוצאה הצפויה היא 8. נבדוק את התוצאה שהפונקציה מחזירה בהשוואה לתוצאה הצפויה
                                                                          אימות:
.הצדקה: הבדיקה חשובה כדי לוודא שהפונקציה מתנהגת כמצופה כאשר אחד מהמספרים הוא מספר שלילי. התוצאה הצפויה מתאימה למפרטים של הפונקציה ולדרישות העסקיות
                                                                                
"""

# ********RoostGPT********
import pytest
from calc import SimpleCalculator

class Test_SimpleCalculatorSubtraction:

    def test_subtraction_basic(self):
        # Arrange
        calc = SimpleCalculator()
        num1 = 5
        num2 = 3
        expected_result = 2

        # Act
        result = calc.subtraction(num1, num2)

        # Assert
        assert result == expected_result, f"For {num1} - {num2}, expected {expected_result} but got {result}"

    def test_subtraction_negative_number(self):
        # Arrange
        calc = SimpleCalculator()
        num1 = 5
        num2 = -3
        expected_result = 8

        # Act
        result = calc.subtraction(num1, num2)

        # Assert
        assert result == expected_result, f"For {num1} - {num2}, expected {expected_result} but got {result}"
