# ********RoostGPT********

# Test generated by RoostGPT for test testing_karate_cli using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /kafka/v3/clusters/{cluster_id}/topics_post for http method type POST 
# RoostTestHash=aeb4a5e71e
# 
# 

# ********RoostGPT********
Feature: Testing /kafka/v3/clusters/{cluster_id}/topics endpoint

  Background:
    * def baseURL = karate.properties['CONFLUENT_CLOUD_APIS_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL

  Scenario Outline: Test POST /kafka/v3/clusters/{cluster_id}/topics endpoint with valid payloads
    * def username = karate.properties['BASIC_USERNAME']
    * def password = karate.properties['BASIC_PASSWORD']
    * def credentials = username + ':' + password
    * def encoded = Java.type('java.util.Base64').getEncoder().encodeToString(credentials.getBytes())
    * def authHeader = 'Basic ' + encoded
    * configure headers = { Authorization: '#(authHeader)', Accept: 'application/json' }
    Given path '/kafka/v3/clusters/', '<cluster_id>', '/topics'
    And request
      """
      {
        "topic_name": "<topic_name>",
        "partitions_count": <partitions_count>,
        "replication_factor": <replication_factor>,
        "configs": [
          {
            "name": "<config_name>",
            "value": "<config_value>"
          }
        ],
        "validate_only": <validate_only>
      }
      """
    When method post
    Then status 201
    And match response == '#object'

    Examples:
      | read('kafka_v3_clusters_cluster_id_topics_post.csv') |

  Scenario Outline: Test POST /kafka/v3/clusters/{cluster_id}/topics endpoint with OAuth2 authorization
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }
    Given path '/kafka/v3/clusters/', '<cluster_id>', '/topics'
    And request
      """
      {
        "topic_name": "<topic_name>",
        "partitions_count": <partitions_count>,
        "replication_factor": <replication_factor>,
        "configs": [
          {
            "name": "<config_name>",
            "value": "<config_value>"
          }
        ],
        "validate_only": <validate_only>
      }
      """
    When method post
    Then status 201
    And match response == '#object'

    Examples:
      | read('kafka_v3_clusters_cluster_id_topics_post.csv') |
