# ********RoostGPT********

# Test generated by RoostGPT for test testing_karate_cli using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /kafka/v3/clusters/{cluster_id}/topics/{topic_name}_delete for http method type DELETE 
# RoostTestHash=a64fff4571
# 
# 

# ********RoostGPT********
Feature: Delete a topic in a cluster

  Background:
    * def baseURL = karate.properties['CONFLUENT_CLOUD_APIS_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL

  @deleteTopicBasicAuth
  Scenario Outline: Delete a topic in a cluster with Basic Auth
    * def username = karate.properties['BASIC_USERNAME']
    * def password = karate.properties['BASIC_PASSWORD']
    * def credentials = username + ':' + password
    * def encoded = Java.type('java.util.Base64').getEncoder().encodeToString(credentials.getBytes())
    * def authHeader = 'Basic ' + encoded
    * configure headers = { Authorization: '#(authHeader)', Accept: 'application/json' }
    Given path '/kafka/v3/clusters/', '<cluster_id>', '/topics/', '<topic_name>'
    When method delete
    Then status 204

    Examples:
      | read('kafka_v3_clusters_cluster_id_topics_topic_name_delete.csv') |

  @deleteTopicOAuth2
  Scenario Outline: Delete a topic in a cluster with OAuth2
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }
    Given path '/kafka/v3/clusters/', '<cluster_id>', '/topics/', '<topic_name>'
    When method delete
    Then status 204

    Examples:
      | read('kafka_v3_clusters_cluster_id_topics_topic_name_delete.csv') |

  @deleteTopicInvalidClusterId
  Scenario Outline: Delete a topic in a cluster with invalid cluster_id
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }
    Given path '/kafka/v3/clusters/', '<cluster_id>', '/topics/', '<topic_name>'
    When method delete
    Then status 404

    Examples:
      | cluster_id | topic_name |
      | 'invalid'  | 'topic1'   |
      | 'invalid'  | 'topic2'   |

  @deleteTopicInvalidTopicName
  Scenario Outline: Delete a topic in a cluster with invalid topic_name
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }
    Given path '/kafka/v3/clusters/', '<cluster_id>', '/topics/', '<topic_name>'
    When method delete
    Then status 404

    Examples:
      | cluster_id | topic_name |
      | 'cluster1' | 'invalid'  |
      | 'cluster2' | 'invalid'  |
