# ********RoostGPT********

# Test generated by RoostGPT for test testing_karate_cli using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /kafka/v3/clusters/{cluster_id}/topics/{topic_name}/records_post for http method type POST 
# RoostTestHash=bc10633495
# 
# 

# ********RoostGPT********
