# ********RoostGPT********

# Test generated by RoostGPT for test testing_karate_cli using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /kafka/v3/clusters/{cluster_id}/topics_get for http method type GET 
# RoostTestHash=19dd095790
# 
# 

# ********RoostGPT********
