# ********RoostGPT********

# Test generated by RoostGPT for test testing_karate_cli using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /kafka/v3/clusters/{cluster_id}/topics/{topic_name}_patch for http method type PATCH 
# RoostTestHash=2d05ffd4ba
# 
# 

# ********RoostGPT********
Feature: Kafka Cluster Topic API

  Background:
    * def baseURL = karate.properties['CONFLUENT_CLOUD_APIS_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL

  Scenario Outline: Patch Kafka Cluster Topic with Basic Auth
    * def username = karate.properties['BASIC_USERNAME']
    * def password = karate.properties['BASIC_PASSWORD']
    * def credentials = username + ':' + password
    * def encoded = Java.type('java.util.Base64').getEncoder().encodeToString(credentials.getBytes())
    * def authHeader = 'Basic ' + encoded
    * configure headers = { Authorization: '#(authHeader)', Accept: 'application/json' }
    Given path '/kafka/v3/clusters/', '<cluster_id>', '/topics/', '<topic_name>'
    And request { partitions_count: '<partitions_count>' }
    When method patch
    Then status 200

    Examples:
      | read('kafka_v3_clusters_cluster_id_topics_topic_name_patch.csv') |

  Scenario Outline: Patch Kafka Cluster Topic with OAuth2
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }
    Given path '/kafka/v3/clusters/', '<cluster_id>', '/topics/', '<topic_name>'
    And request { partitions_count: '<partitions_count>' }
    When method patch
    Then status 200

    Examples:
      | read('kafka_v3_clusters_cluster_id_topics_topic_name_patch.csv') |

  Scenario Outline: Patch Kafka Cluster Topic with Invalid Data
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }
    Given path '/kafka/v3/clusters/', '<cluster_id>', '/topics/', '<topic_name>'
    And request { partitions_count: '<partitions_count>' }
    When method patch
    Then match responseStatus == '<status_code>'

    Examples:
      | cluster_id | topic_name | partitions_count | status_code |
      | 'test1'    | 'test1'    | 'invalid'        |         400 |
      | 'test2'    | 'test2'    |               -1 |         400 |
      | 'test3'    | 'test3'    |                0 |         400 |
