# ********RoostGPT********

# Test generated by RoostGPT for test testing_karate_cli using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /kafka/v3/clusters/{cluster_id}/topics/{topic_name}_get for http method type GET 
# RoostTestHash=c8640c53d0
# 
# 

# ********RoostGPT********
Feature: Kafka Cluster Topic API

  Background:
    * def baseURL = karate.properties['CONFLUENT_CLOUD_APIS_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL

  Scenario Outline: Get Kafka Cluster Topic with Basic Auth
    * def username = karate.properties['BASIC_USERNAME']
    * def password = karate.properties['BASIC_PASSWORD']
    * def credentials = username + ':' + password
    * def encoded = Java.type('java.util.Base64').getEncoder().encodeToString(credentials.getBytes())
    * def authHeader = 'Basic ' + encoded
    * configure headers = { Authorization: '#(authHeader)', Accept: 'application/json' }
    Given path '/kafka/v3/clusters/', '<cluster_id>', '/topics/', '<topic_name>'
    And param include_authorized_operations = <include_authorized_operations>
    When method get
    Then status <status_code>
    And match response == '<response_body>'

    Examples:
      | cluster_id | topic_name | include_authorized_operations | status_code | response_body |
      | 'test1'    | 'test1'    | true                          |         200 | '#object'     |
      | 'test2'    | 'test2'    | false                         |         400 | '#object'     |
      | 'test3'    | 'test3'    | true                          |         401 | '#object'     |
      | 'test4'    | 'test4'    | false                         |         403 | '#object'     |
      | 'test5'    | 'test5'    | true                          |         404 | '#object'     |
      | 'test6'    | 'test6'    | false                         |         429 | '#object'     |
      | 'test7'    | 'test7'    | true                          |         500 | '#object'     |

  Scenario Outline: Get Kafka Cluster Topic with OAuth2
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }
    Given path '/kafka/v3/clusters/', '<cluster_id>', '/topics/', '<topic_name>'
    And param include_authorized_operations = <include_authorized_operations>
    When method get
    Then status <status_code>
    And match response == '<response_body>'

    Examples:
      | cluster_id | topic_name | include_authorized_operations | status_code | response_body |
      | 'test1'    | 'test1'    | true                          |         200 | '#object'     |
      | 'test2'    | 'test2'    | false                         |         400 | '#object'     |
      | 'test3'    | 'test3'    | true                          |         401 | '#object'     |
      | 'test4'    | 'test4'    | false                         |         403 | '#object'     |
      | 'test5'    | 'test5'    | true                          |         404 | '#object'     |
      | 'test6'    | 'test6'    | false                         |         429 | '#object'     |
      | 'test7'    | 'test7'    | true                          |         500 | '#object'     |
