# ********RoostGPT********

# Test generated by RoostGPT for test testing_karate_cli using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /kafka/v3/clusters/{cluster_id}/topics/{topic_name}/partitions_get for http method type GET 
# RoostTestHash=ad1b66161d
# 
# 

# ********RoostGPT********
Feature: Test /kafka/v3/clusters/{cluster_id}/topics/{topic_name}/partitions endpoint

  Background:
    * def baseURL = karate.properties['CONFLUENT_CLOUD_APIS_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL

  Scenario Outline: Test GET method with valid parameters and basic auth
    * def username = karate.properties['BASIC_USERNAME']
    * def password = karate.properties['BASIC_PASSWORD']
    * def credentials = username + ':' + password
    * def encoded = Java.type('java.util.Base64').getEncoder().encodeToString(credentials.getBytes())
    * def authHeader = 'Basic ' + encoded
    * configure headers = { Authorization: '#(authHeader)', Accept: 'application/json' }
    Given path 'kafka/v3/clusters', '<cluster_id>', 'topics', '<topic_name>', 'partitions'
    When method get
    Then status 200
    And match response == '#object'

    Examples:
      | read('kafka_v3_clusters_cluster_id_topics_topic_name_partitions_get.csv') |

  Scenario Outline: Test GET method with valid parameters and oauth2 auth
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }
    Given path 'kafka/v3/clusters', '<cluster_id>', 'topics', '<topic_name>', 'partitions'
    When method get
    Then status 200
    And match response == '#object'

    Examples:
      | read('kafka_v3_clusters_cluster_id_topics_topic_name_partitions_get.csv') |

  Scenario Outline: Test GET method with invalid parameters
    * def username = karate.properties['BASIC_USERNAME']
    * def password = karate.properties['BASIC_PASSWORD']
    * def credentials = username + ':' + password
    * def encoded = Java.type('java.util.Base64').getEncoder().encodeToString(credentials.getBytes())
    * def authHeader = 'Basic ' + encoded
    * configure headers = { Authorization: '#(authHeader)', Accept: 'application/json' }
    Given path 'kafka/v3/clusters', '<cluster_id>', 'topics', '<topic_name>', 'partitions'
    When method get
    Then status 400
    And match response.id == '#string'
    And match response.status == '#string'
    And match response.code == '#string'
    And match response.title == '#string'
    And match response.detail == '#string'
    And match response.source == '#object'
    And match response.source.pointer == '#string'
    And match response.source.parameter == '#string'
    And match response.error_code == '#number'
    And match response.message == '##string'

    Examples:
      | cluster_id       | topic_name     |
      | 'invalidCluster' | 'testTopic1'   |
      | 'testCluster1'   | 'invalidTopic' |
